on: 
  workflow_dispatch

jobs:
  build:
    name: download Vulkan SDK
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - shell: pwsh
        run: |
          Get-ChildItem -Directory -Exclude .* . | Remove-Item -Recurse -Force
          $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
          echo Version $ver
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/windows/VulkanSDK-$ver-Installer.exe" -OutFile VulkanSDK.exe
          echo Downloaded
          .\VulkanSDK.exe --root D:\VulkanSDK --accept-licenses --default-answer --confirm-command install com.lunarg.vulkan.debug  
          Get-ChildItem D:\VulkanSDK
          Copy-Item -Path D:\VulkanSDK\Bin -Destination ./Bin -Recurse
          Copy-Item -Path D:\VulkanSDK\Config -Destination ./Config -Recurse
          Copy-Item -Path D:\VulkanSDK\Include -Destination ./Include -Recurse
          Copy-Item -Path D:\VulkanSDK\Lib -Destination ./Lib -Recurse
          Copy-Item -Path D:\VulkanSDK\share -Destination ./share -Recurse

      - uses: EndBug/add-and-commit@v9
        with:
          message: 'updated to latest VulkanSDK'
        
